-- 청경에너지: 8명
WITH target_co AS (SELECT id FROM public.companies WHERE name = '청경에너지'),
     target_ws AS (SELECT id, name FROM public.worksites WHERE company_id = (SELECT id FROM target_co) ORDER BY order_idx),
     target_dep AS (SELECT id, name, worksite_id FROM public.departments WHERE company_id = (SELECT id FROM target_co) AND parent_department_id IS NULL ORDER BY order_idx)
INSERT INTO public.employees (employee_no, name, company_id, worksite_id, department_id, rank_code, birth_date, hire_date, termination_date, gender, employment_type_code, nationality_type, nationality, accounting_type_code, job_family_code, annual_salary, hire_channel_code, education_code, career_before_join_years, total_career_years, status_code, termination_reason_code) VALUES
('T2600658', '정승현', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '대리', '1986-06-23', '2026-06-21', '2026-09-25', '남', '계약직', '내국인', '대한민국', '제조', '생산', 38470330, '직채용', '고졸', 11.8, 11.8, '퇴직', '자발'),
('T2400659', '오기태', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '대리', '1996-01-06', '2024-06-23', NULL, '남', '정규직', '내국인', '대한민국', '판관', '생산', 35101500, '직채용', '전문학사', 1.0, 3.0, '재직', NULL),
('T2500660', '전형남', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1980-08-22', '2025-04-09', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 24420780, '기타', '석사', 0, 1, '재직', NULL),
('T2400661', '장우진', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1983-10-25', '2024-09-06', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 30956320, '직채용', '미기재', 0, 2, '재직', NULL),
('T1900662', '권우진', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1985-05-10', '2019-11-05', NULL, '남', '정규직', '내국인', '대한민국', '제조', '생산', 26476560, '추천', '전문학사', 0, 7, '재직', NULL),
('T1900663', '김지원', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1972-08-22', '2019-08-18', NULL, '남', '정규직', '내국인', '대한민국', '제조', '생산', 28859980, '직채용', '학사', 0, 7, '재직', NULL),
('T2500664', '정우진', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '과장', '1976-09-03', '2025-11-24', NULL, '남', '정규직', '내국인', '대한민국', '제조', '관리', 50761630, '직채용', '고졸', 9.8, 10.8, '재직', NULL),
('T1900665', '박석준', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1978-02-11', '2019-01-07', NULL, '남', '정규직', '내국인', '대한민국', '제조', '생산', 25886130, '직채용', '고졸', 0, 7, '재직', NULL);