-- 신진유화: 5명
WITH target_co AS (SELECT id FROM public.companies WHERE name = '신진유화'),
     target_ws AS (SELECT id, name FROM public.worksites WHERE company_id = (SELECT id FROM target_co) ORDER BY order_idx),
     target_dep AS (SELECT id, name, worksite_id FROM public.departments WHERE company_id = (SELECT id FROM target_co) AND parent_department_id IS NULL ORDER BY order_idx)
INSERT INTO public.employees (employee_no, name, company_id, worksite_id, department_id, rank_code, birth_date, hire_date, termination_date, gender, employment_type_code, nationality_type, nationality, accounting_type_code, job_family_code, annual_salary, hire_channel_code, education_code, career_before_join_years, total_career_years, status_code, termination_reason_code) VALUES
('T2100804', '강건우', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1961-07-04', '2021-01-10', NULL, '남', '정규직', '내국인', '대한민국', '제조', '생산', 24805520, '직채용', '전문학사', 0.1, 5.1, '재직', NULL),
('T1900805', '이지혜', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1966-12-15', '2019-11-19', NULL, '여', '계약직', '내국인', '대한민국', '제조', '생산', 25217280, '직채용', '고졸', 7.4, 14.4, '재직', NULL),
('T2400806', '신준호', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1996-08-02', '2024-11-18', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 29843520, '직채용', '고졸', 0, 2, '재직', NULL),
('T2300807', '황우진', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '차장', '2000-02-19', '2023-03-04', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 58838300, '기타', '전문학사', 0.3, 3.3, '재직', NULL),
('T2300808', '신성민', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '차장', '1982-12-23', '2023-04-05', NULL, '남', '계약직', '내국인', '대한민국', '판관', '관리', 55699580, '직채용', '고졸', 12.7, 15.7, '재직', NULL);