-- 제이에스자원환경: 11명
WITH target_co AS (SELECT id FROM public.companies WHERE name = '제이에스자원환경'),
     target_ws AS (SELECT id, name FROM public.worksites WHERE company_id = (SELECT id FROM target_co) ORDER BY order_idx),
     target_dep AS (SELECT id, name, worksite_id FROM public.departments WHERE company_id = (SELECT id FROM target_co) AND parent_department_id IS NULL ORDER BY order_idx)
INSERT INTO public.employees (employee_no, name, company_id, worksite_id, department_id, rank_code, birth_date, hire_date, termination_date, gender, employment_type_code, nationality_type, nationality, accounting_type_code, job_family_code, annual_salary, hire_channel_code, education_code, career_before_join_years, total_career_years, status_code, termination_reason_code) VALUES
('T1900281', '띠엔', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1982-05-26', '2019-06-19', NULL, '남', '계약직', '외국인', '필리핀', '제조', '생산', 29981990, '직채용', '미기재', 0, 7, '재직', NULL),
('T2400282', '티', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1966-02-25', '2024-01-24', NULL, '여', '계약직', '외국인', '미얀마', '제조', '생산', 27506320, '직채용', '학사', 4.2, 6.2, '재직', NULL),
('T2400283', '홍민수', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1969-06-18', '2024-01-10', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 27427070, '직채용', '고졸', 0.5, 2.5, '재직', NULL),
('T2000284', '안영민', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1990-02-16', '2020-07-05', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 24517060, '직채용', '고졸', 0, 6, '재직', NULL),
('T2300285', '황진우', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1968-04-03', '2023-09-20', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 28509560, '직채용', '미기재', 0.9, 3.9, '재직', NULL),
('T2500286', '응오', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1975-08-02', '2025-06-20', NULL, '남', '계약직', '외국인', '캄보디아', '제조', '생산', 26448310, '직채용', '전문학사', 0, 1, '휴직', NULL),
('T2500287', '루안', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1996-08-16', '2025-01-11', NULL, '남', '계약직', '외국인', '캄보디아', '제조', '생산', 26191620, '직채용', '고졸', 0, 1, '재직', NULL),
('T2200288', '정준호', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1997-04-26', '2022-05-06', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 26844590, '직채용', '학사', 0, 4, '재직', NULL),
('T1500289', '오현우', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '전무', '1961-06-16', '2015-04-13', NULL, '남', '임원', '내국인', '대한민국', '제조', '관리', 106682860, '직채용', '전문학사', 0.2, 11.2, '재직', NULL),
('T2200290', '강준호', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1981-09-09', '2022-06-21', NULL, '남', '계약직', '내국인', '대한민국', '제조', '생산', 30561900, '직채용', '전문학사', 0, 4, '재직', NULL),
('T2100291', '윤혜진', (SELECT id FROM target_co), (SELECT id FROM target_ws ORDER BY random() LIMIT 1), (SELECT id FROM target_dep WHERE worksite_id = (SELECT id FROM target_ws ORDER BY random() LIMIT 1) ORDER BY random() LIMIT 1), '사원', '1994-09-22', '2021-11-05', NULL, '여', '고문', '내국인', '대한민국', '제조', '생산', 30559100, '직채용', '전문학사', 0, 5, '재직', NULL);